name: Deploy to Firebase Hosting preview channel on push
on:
  push:
    branches:
      - preview
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RUKN_APP }}'
          projectId: rukn-app
          channelId: pre-release-2023
