name: Deploy to Firebase Hosting LIVE channel
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'images/**'
      - '.gitignore'
      - 'README*.md'
      - 'LICENSE*'
jobs:
  build_and_deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RUKN_APP }}'
          projectId: rukn-app
          channelId: live
